name: Build and Attach Release

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      # Checkout the repository.
      - uses: actions/checkout@v4

      # Build the project in release mode.
      - name: Build
        run: cargo build --release --verbose

      # Upload .exe file to Release
      - name: Upload .exe to Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/antibloatlight.exe
